apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-biometric-grant
  annotations:
    kubernetes.io/ingress.class: "kcorp"
config:
  replace:
    uri: "/v1/auth/biometric/verification"
plugin: request-transformer