apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-password-grant
  annotations:
    kubernetes.io/ingress.class: "kong"
config:
  replace:
    uri: "/v1/v1/auth/mfa/verification" # "/v1/auth/mfa/verification"
plugin: request-transformer