apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-activation-password-grant
config:
  replace:
    uri: "/v1/auth/activation/password/verification"
plugin: request-transformer