apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-prelogin-grant
  annotations:
    kubernetes.io/ingress.class: "kcorp"
config:
  replace:
    uri: "/v1/profile/preload"
plugin: request-transformer