apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: biometric-grant
  annotations:
    konghq.com/plugins: basic-auth, request-transformer-biometric-grant
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "corp-kong"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 80
        path: /v1/biometric/grant
