apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: activation-password-grant
  annotations:
    konghq.com/plugins: request-transformer-activation-password-grant, upstream-jwt, custom-oauth2, custom-response-transformer
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: localization
          servicePort: 8080
        path: /v1/activation/password/grant
