apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: biometric-grant
  annotations:
    konghq.com/plugins: basic-auth, request-transformer-biometric-grant, upstream-jwt, custom-oauth2, custom-response-transformer
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "arief-test"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: localization
          servicePort: 8080
        path: /v1/biometric/grant
