apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: password-grant
  annotations:
    konghq.com/plugins: request-transformer-password-grant, upstream-jwt, custom-oauth2, custom-response-transformer, session
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "kcorp"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kcorp-demo
          servicePort: 8080
        path: /v1/password/grant
