apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: password-grant
  annotations:
    konghq.com/plugins: basic-auth, request-transformer-password-grant
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "arief-test"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 80
        path: /v1/password/grant
