apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pin-grant
  annotations:
    konghq.com/plugins: basic-auth
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 80
        path: /v1/pin/grant
