apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: subsequent
  annotations:
    konghq.com/plugins: custom-oauth2, kong-upstream-jwt
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: push-notification
          servicePort: 8080
        path: /subsequent