apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    konghq.com/plugins: upstream-jwt
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: "arief-test"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: httpbin
          servicePort: 80
        path: /test